# -------------------------------------------------------------------------
# Module 02: Importing Data
# Goal: Handle "real world" messy files (skip rows, missing values).
# -------------------------------------------------------------------------

# Install packages if needed (run once):
# install.packages("tidyverse")
# install.packages("readxl")

library(tidyverse)
library(readxl)

# --- STEP 1: GENERATE DUMMY DATA (Run this once to create the file) ---
# We create a text file that looks like a messy server log export
messy_content <- "
# REPORT GENERATED BY: SERVER_ADMIN_01
# DATE: 2023-10-01
# CONFIDENTIAL
ServerID,Status,Uptime_Days,Last_Error
srv-01,OK,120,None
srv-02,FAIL,-,Connection Timeout
srv-03,OK,15,NULL
srv-04,WARN,999,Memory Leak
"
writeLines(messy_content, "messy_data.csv")
print("Created 'messy_data.csv' in your working directory.")


# --- STEP 2: READ THE MESSY DATA ---

# Attempt 1: Naive read (Will likely look weird)
print("--- Attempt 1: Raw Read ---")
df_bad <- read_csv("messy_data.csv")
print(df_bad) 
# Notice the column names are weird (like `# REPORT...`)

# Attempt 2: Clean read
print("--- Attempt 2: Clean Read ---")
df_clean <- read_csv(
  "messy_data.csv",
  skip = 4,                      # Skip the first 4 metadata lines
  na = c("", "NA", "-", "NULL"), # Define what counts as 'Missing'
  col_types = cols(              # Force specific types (optional but safe)
    ServerID = col_character(),
    Status = col_character(),
    Uptime_Days = col_double(),
    Last_Error = col_character()
  )
)

print(df_clean)

# --- STEP 3: EXPORT RESULTS ---
# Save the cleaned version for your boss
write_csv(df_clean, "clean_server_report.csv")
print("Saved 'clean_server_report.csv'.")

